name: "Continuous Integration (CI)"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code-analysis:
    name: "Code Analysis"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - name: Run download dependencies
        run: go mod download -x
      - name: Run verify modules
        run: go mod verify
      - name: Run unit tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.6"
          install-go: false
          cache-key: "1.19"
      - name: Run sonar cloud
        uses: sonarsource/sonarcloud-github-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
